// kafka-connector options: START
[[camel-webhook-source-kafka-connector-source]]
= camel-webhook-source-kafka-connector source configuration

Connector description: Creates an HTTP endpoint that can be used as a bridge to forward data to the Kamelet sink.

The "subpath" parameter of the Webhook source allows to customize the subpath where the integration will respond to HTTP requests.
It's common to use a non-guessable ID for that parameter.

When the "subpath" parameter is set to "webhook" (default), the integration will accept requests at the "https://integration-external-url/webhook" endpoint.

When using camel-webhook-source-kafka-connector as source make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-webhook-source-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Source connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.webhooksource.CamelWebhooksourceSourceConnector
----


The camel-webhook-source source connector supports 1 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.webhook-source.subpath* | The subpath where the webhook is registered  | "webhook" | false | MEDIUM
|===



The camel-webhook-source source connector has no converters out of the box.





The camel-webhook-source source connector has no transforms out of the box.





The camel-webhook-source source connector has no aggregation strategies out of the box.




// kafka-connector options: END
