== Camel Kafka Connector

=== Introduction
[NOTE]
====
*The project is WIP!*
====

This is a "Camel Kafka connector adapter" that aims to provide a user friendly way to use all Apache Camel components in Kafka Connect.
For more information about Kafka Connect take a look http://kafka.apache.org/documentation/#connect[here].

=== Build the project
[source,bash]
----
mvn clean package
----

=== Try it out locally

You can use Camel Kafka connectors with local Apache Kafka installation.
For more details see the [local guide](./docs/try-it-out-locally.adoc).

=== Try it out on OpenShift with Strimzi

You can also use Camel Kafka connectors on OpenShift.
For more details see the [OpenShift Guide](./docs/try-it-out-on-openshift-with-strimzi.adoc).

=== Known limitations
In order to use other Camel components you need to add them as dependencies in the project `pom.xml`.

Following camel component, which are based on `DataFormats`, are not yet supported:

* camel-asn1
* camel-avro
* camel-barcode
* camel-base64
* camel-beanio
* camel-bindy-csv
* camel-bindy-fixed
* camel-bindy-kvp
* camel-boon
* camel-cbor
* camel-crypto
* camel-csv
* camel-fhirJson
* camel-fhirXml
* camel-flatpack
* camel-grok
* camel-gzipdeflater
* camel-hl7
* camel-ical
* camel-jacksonxml
* camel-jaxb
* camel-json-fastjson
* camel-json-gson
* camel-json-jackson
* camel-json-johnzon
* camel-json-xstream
* camel-jsonApi
* camel-lzf
* camel-mime-multipart
* camel-pgp
* camel-protobuf
* camel-rss
* camel-secureXML
* camel-soapjaxb
* camel-syslog
* camel-tarfile
* camel-thrift
* camel-tidyMarkup
* camel-univocity-csv
* camel-univocity-fixed
* camel-univocity-tsv
* camel-xstream
* camel-yaml-snakeyaml
* camel-zipdeflater
* camel-zipfile
