[[WhatIsIt-WhatIsIt]]
= Camel Kafka Connector

[NOTE]
--
This version ({page-component-display-version}) of {page-component-title} depends on:

* https://kafka.apache.org[Apache Kafka] at version {kafka-version}
* xref:{camel-docs-version}@components::index.adoc[Camel] at version {camel-version}
//* xref:{camel-kamelets-docs-version}@camel-kamelets::index.adoc[Camel Kamelets] at version {camel-kamelets-version}

ifdef::lts[This long term service release will be supported until {lts}.]
ifndef::lts[]
ifdef::prerelease[This is the development version of {page-component-title}. It should not be used in production.]
ifndef::prerelease[This release will not be updated, but rather replaced by a new release.]
endif::[]
--

Camel Kafka Connector allows you to use all Camel xref:components::index.adoc[components] as http://kafka.apache.org/documentation/#connect[Kafka Connect] connectors.

The basic idea is reusing the available Camel components as Kafka sink and source connectors in a simple way.

== Where to go next?

* xref:user-guide/index.adoc[User guide]
* xref:contributor-guide/index.adoc[Contributor guide]
* xref:reference/index.adoc[Connectors reference]

== Compatibility Matrix

[caption=]
.Compatibility between Camel-Kafka-Connector and dependencies
[width="100%",cols="4,2,2,2,1,3",options="header",]
|===
|Camel-Kafka-Connector Version
|Camel Version
|Kamelets Version
|Kafka Version
|LTS Until
|Branch
|===

//cannot use top level index.adoc as the page with the query is always omitted.
indexTable::[version="*",relative="reference/index.adoc",cellformats="ckc.ckcRef(pageComponentVersion, pageComponentDisplayVersion)|ckc.camelRef(camelVersion, camelDocsVersion)|ckc.kameletsRef(camelKameletsVersion, camelKameletsDocsVersion)|ckc.kafkaRef(kafkaVersion, kafkaDocsVersion)|lts|ckc.branch(pageComponentVersion)", requires={requires}]
