[[SingleMessageTransformations-SingleMessageTransformations]]
= Single Message Transformations

Single Message Transforms (SMTs) is a Kafka API that provides a simple interface for
manipulating records as they flow through both the source and sink side of your
data pipeline. It operates on every single message in your data pipeline as it
passes through the Kafka Connect connector.
Single Message Transformations are applied to messages as they flow through Connect.
SMTs transform inbound messages after a source connector has produced them,
but before they are written to Kafka. SMTs transform outbound messages before they
are sent to a sink connector. The following SMTs are available for use with Kafka Connect.

In addition to the https://docs.confluent.io/current/connect/transforms/index.html?_ga=2.114132679.1300749793.1612453936-340332144.1608111036&_gac=1.228771694.1611682559.CjwKCAiAxp-ABhALEiwAXm6IyeFH3rDEIpDWXGQaoibWgcjXxdz8YLkAbi3n8O-quiuWzdAeNezaqhoCdmgQAvD_BwE[prebuilt transformations]#,#
Camel Kafka Connector provides additionals SMTs:

[cols="^,^ ", options="header"]
|===
|Transform | Description

|xref:transformers/fieldsToHeaders.adoc[FieldsToHeaders]
|Extract fields from a configured record value (struct, schema and map are supported)
and copy the value in configured headers
|===
