// kafka-connector options: START
[[camel-aws-ec2-sink-kafka-connector-sink]]
= camel-aws-ec2-sink-kafka-connector sink configuration

Connector Description: Check the status of EC2 instances

The Kamelet expects the following headers to be set:

- `instanceIds` / `ce-instanceIds`: as a comma separated list of EC2 instance ids.

When using camel-aws-ec2-sink-kafka-connector as sink make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-aws-ec2-sink-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Sink connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.awsec2sink.CamelAwsec2sinkSinkConnector
----


The camel-aws-ec2-sink sink connector supports 3 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.aws-ec2-sink.accessKey* | The access key obtained from AWS | null | true | HIGH
| *camel.kamelet.aws-ec2-sink.secretKey* | The secret key obtained from AWS | null | true | HIGH
| *camel.kamelet.aws-ec2-sink.region* | The AWS region to connect to Example: eu-west-1 | null | true | HIGH
|===



The camel-aws-ec2-sink sink connector has no converters out of the box.





The camel-aws-ec2-sink sink connector has no transforms out of the box.





The camel-aws-ec2-sink sink connector has no aggregation strategies out of the box.




// kafka-connector options: END
