// kafka-connector options: START
[[camel-aws-s3-source-kafka-connector-source]]
= camel-aws-s3-source-kafka-connector source configuration

Connector description: Receive data from AWS S3.

When using camel-aws-s3-source-kafka-connector as source make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-aws-s3-source-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Source connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.awss3source.CamelAwss3sourceSourceConnector
----


The camel-aws-s3-source source connector supports 7 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.aws-s3-source.bucketNameOrArn* | The S3 Bucket name or ARN | null | true | HIGH
| *camel.kamelet.aws-s3-source.deleteAfterRead* | Delete objects after consuming them | true | false | MEDIUM
| *camel.kamelet.aws-s3-source.accessKey* | The access key obtained from AWS | null | true | HIGH
| *camel.kamelet.aws-s3-source.secretKey* | The secret key obtained from AWS | null | true | HIGH
| *camel.kamelet.aws-s3-source.region* | The AWS region to connect to Example: eu-west-1 | null | true | HIGH
| *camel.kamelet.aws-s3-source.autoCreateBucket* | Setting the autocreation of the S3 bucket bucketName. | false | false | MEDIUM
| *camel.kamelet.aws-s3-source.includeBody* | If it is true, the exchange will be consumed and put into the body and closed. If false the S3Object stream will be put raw into the body and the headers will be set with the S3 object metadata. | true | false | MEDIUM
|===



The camel-aws-s3-source source connector has no converters out of the box.





The camel-aws-s3-source source connector has no transforms out of the box.





The camel-aws-s3-source source connector has no aggregation strategies out of the box.
// kafka-connector options: END
