// kafka-connector options: START
[[camel-dropbox-source-kafka-connector-source]]
= camel-dropbox-source-kafka-connector source configuration

Connector description: Consume Files from Dropbox.

When using camel-dropbox-source-kafka-connector as source make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-dropbox-source-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Source connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.dropboxsource.CamelDropboxsourceSourceConnector
----


The camel-dropbox-source source connector supports 5 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.dropbox-source.period* | The interval between fetches to the Dropbox remote path in milliseconds | 10000 | true | HIGH
| *camel.kamelet.dropbox-source.accessToken* | The access Token to use to access Dropbox | null | true | HIGH
| *camel.kamelet.dropbox-source.clientIdentifier* | Dropbox App client Identifier | null | true | HIGH
| *camel.kamelet.dropbox-source.remotePath* | Original file or folder to work with | null | true | HIGH
| *camel.kamelet.dropbox-source.query* | A space-separated list of sub-strings to search for. A file matches only if it contains all the sub-strings. If this option is not set, all files will be matched. | null | true | HIGH
|===



The camel-dropbox-source source connector has no converters out of the box.





The camel-dropbox-source source connector has no transforms out of the box.





The camel-dropbox-source source connector has no aggregation strategies out of the box.
// kafka-connector options: END
