// kafka-connector options: START
[[camel-http-sink-kafka-connector-sink]]
= camel-http-sink-kafka-connector sink configuration

Connector Description: Forwards an event to a HTTP endpoint

When using camel-http-sink-kafka-connector as sink make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-http-sink-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Sink connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.httpsink.CamelHttpsinkSinkConnector
----


The camel-http-sink sink connector supports 2 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.http-sink.url* | The URL to send data to Example: \https://my-service/path | null | true | HIGH
| *camel.kamelet.http-sink.method* | The HTTP method to use | "POST" | false | MEDIUM
|===



The camel-http-sink sink connector has no converters out of the box.





The camel-http-sink sink connector has no transforms out of the box.





The camel-http-sink sink connector has no aggregation strategies out of the box.
// kafka-connector options: END
