// kafka-connector options: START
[[camel-aws-kinesis-source-kafka-connector-source]]
= camel-aws-kinesis-source-kafka-connector source configuration

Connector description: Receive data from AWS Kinesis.

When using camel-aws-kinesis-source-kafka-connector as source make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-aws-kinesis-source-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Source connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.awskinesissource.CamelAwskinesissourceSourceConnector
----


The camel-aws-kinesis-source source connector supports 4 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.aws-kinesis-source.stream* | The Kinesis stream that you want to access (needs to be created in advance) | null | true | HIGH
| *camel.kamelet.aws-kinesis-source.accessKey* | The access key obtained from AWS | null | true | HIGH
| *camel.kamelet.aws-kinesis-source.secretKey* | The secret key obtained from AWS | null | true | HIGH
| *camel.kamelet.aws-kinesis-source.region* | The AWS region to connect to Example: eu-west-1 | null | true | HIGH
|===



The camel-aws-kinesis-source source connector has no converters out of the box.





The camel-aws-kinesis-source source connector has no transforms out of the box.





The camel-aws-kinesis-source source connector has no aggregation strategies out of the box.
// kafka-connector options: END
