// kafka-connector options: START
[[camel-azure-storage-blob-sink-kafka-connector-sink]]
= camel-azure-storage-blob-sink-kafka-connector sink configuration

Connector Description: Upload data to Azure Storage Blob.

The Kamelet expects the following headers to be set:

- `file` / `ce-file`: as the file name to upload

If the header won't be set the exchange ID will be used as file name.

When using camel-azure-storage-blob-sink-kafka-connector as sink make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-azure-storage-blob-sink-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Sink connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.azurestorageblobsink.CamelAzurestorageblobsinkSinkConnector
----


The camel-azure-storage-blob-sink sink connector supports 4 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.azure-storage-blob-sink.accountName* | The Azure Storage Blob account name. | null | true | HIGH
| *camel.kamelet.azure-storage-blob-sink.container Name* | The Azure Storage Blob container name. | null | true | HIGH
| *camel.kamelet.azure-storage-blob-sink.accessKey* | The Azure Storage Blob access Key. | null | true | HIGH
| *camel.kamelet.azure-storage-blob-sink.operation* | The operation to perform. | "uploadBlockBlob" | false | MEDIUM
|===



The camel-azure-storage-blob-sink sink connector has no converters out of the box.





The camel-azure-storage-blob-sink sink connector has no transforms out of the box.





The camel-azure-storage-blob-sink sink connector has no aggregation strategies out of the box.
// kafka-connector options: END
