// kafka-connector options: START
[[camel-slack-source-kafka-connector-source]]
= camel-slack-source-kafka-connector source configuration

Connector description: Receive messages from a Slack channel.

When using camel-slack-source-kafka-connector as source make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-slack-source-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Source connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.slacksource.CamelSlacksourceSourceConnector
----


The camel-slack-source source connector supports 2 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.slack-source.channel* | The Slack channel to receive messages from Example: #myroom | null | true | HIGH
| *camel.kamelet.slack-source.token* | The token to access Slack. A Slack app is needed. This app needs to have channels:history and channels:read permissions. The Bot User OAuth Access Token is the kind of token needed. | null | true | HIGH
|===



The camel-slack-source source connector has no converters out of the box.





The camel-slack-source source connector has no transforms out of the box.





The camel-slack-source source connector has no aggregation strategies out of the box.
// kafka-connector options: END
