// kafka-connector options: START
[[camel-jms-amqp-10-source-kafka-connector-source]]
= camel-jms-amqp-10-source-kafka-connector source configuration

Connector description: A Kamelet that can consume events from any AMQP 1.0 compliant message broker using the Apache Qpid JMS client

When using camel-jms-amqp-10-source-kafka-connector as source make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-jms-amqp-10-source-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Source connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.jmsamqp10source.CamelJmsamqp10sourceSourceConnector
----


The camel-jms-amqp-10-source source connector supports 3 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.jms-amqp-10-source.destinationType* | The JMS destination type (i.e.: queue or topic) | "queue" | false | MEDIUM
| *camel.kamelet.jms-amqp-10-source.destinationName* | The JMS destination name | null | true | HIGH
| *camel.kamelet.jms-amqp-10-source.remoteURI* | The JMS URL Example: amqp://my-host:31616 | null | true | HIGH
|===



The camel-jms-amqp-10-source source connector has no converters out of the box.





The camel-jms-amqp-10-source source connector has no transforms out of the box.





The camel-jms-amqp-10-source source connector has no aggregation strategies out of the box.
// kafka-connector options: END
