// kafka-connector options: START
[[camel-azure-storage-blob-source-kafka-connector-source]]
= camel-azure-storage-blob-source-kafka-connector source configuration

Connector description: Consume Files from Azure Storage Blob.

When using camel-azure-storage-blob-source-kafka-connector as source make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-azure-storage-blob-source-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Source connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.azurestorageblobsource.CamelAzurestorageblobsourceSourceConnector
----


The camel-azure-storage-blob-source source connector supports 4 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.azure-storage-blob-source.period* | The interval between fetches to the Azure Storage Container in milliseconds | 10000 | true | HIGH
| *camel.kamelet.azure-storage-blob-source.account Name* | The Azure Storage Blob account name. | null | true | HIGH
| *camel.kamelet.azure-storage-blob-source.container Name* | The Azure Storage Blob container name. | null | true | HIGH
| *camel.kamelet.azure-storage-blob-source.accessKey* | The Azure Storage Blob access Key. | null | true | HIGH
|===



The camel-azure-storage-blob-source source connector has no converters out of the box.





The camel-azure-storage-blob-source source connector has no transforms out of the box.





The camel-azure-storage-blob-source source connector has no aggregation strategies out of the box.
// kafka-connector options: END
