// kafka-connector options: START
[[camel-nats-source-kafka-connector-source]]
= camel-nats-source-kafka-connector source configuration

Connector description: Receive data from NATS topics.

When using camel-nats-source-kafka-connector as source make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-nats-source-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Source connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.natssource.CamelNatssourceSourceConnector
----


The camel-nats-source source connector supports 2 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.nats-source.topic* | NATS Topic name | null | true | HIGH
| *camel.kamelet.nats-source.servers* | Comma separated list of NATS Servers | null | true | HIGH
|===



The camel-nats-source source connector has no converters out of the box.





The camel-nats-source source connector has no transforms out of the box.





The camel-nats-source source connector has no aggregation strategies out of the box.
// kafka-connector options: END
