// kafka-connector options: START
[[camel-jms-apache-artemis-sink-kafka-connector-sink]]
= camel-jms-apache-artemis-sink-kafka-connector sink configuration

Connector Description: A Kamelet that can produce events to an Apache Artemis message broker using JMS

When using camel-jms-apache-artemis-sink-kafka-connector as sink make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-jms-apache-artemis-sink-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Sink connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.jmsapacheartemissink.CamelJmsapacheartemissinkSinkConnector
----


The camel-jms-apache-artemis-sink sink connector supports 3 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.jms-apache-artemis-sink.destination Type* | The JMS destination type (i.e.: queue or topic) | "queue" | false | MEDIUM
| *camel.kamelet.jms-apache-artemis-sink.destination Name* | The JMS destination name Example: person | null | true | HIGH
| *camel.kamelet.jms-apache-artemis-sink.brokerURL* | The JMS URL Example: tcp://my-host:61616 | null | true | HIGH
|===



The camel-jms-apache-artemis-sink sink connector has no converters out of the box.





The camel-jms-apache-artemis-sink sink connector has no transforms out of the box.





The camel-jms-apache-artemis-sink sink connector has no aggregation strategies out of the box.
// kafka-connector options: END
