// kafka-connector options: START
[[camel-file-watch-source-kafka-connector-source]]
= camel-file-watch-source-kafka-connector source configuration

Connector description: Receive events related to a file or folder. It may require a volume mounting on Kubernetes.

When using camel-file-watch-source-kafka-connector as source make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-file-watch-source-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Source connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.filewatchsource.CamelFilewatchsourceSourceConnector
----


The camel-file-watch-source source connector supports 2 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.file-watch-source.path* | Path of file or folder to watch | null | true | HIGH
| *camel.kamelet.file-watch-source.events* | The type of events to consume | "CREATE,MODIFY,DELETE" | true | HIGH
|===



The camel-file-watch-source source connector has no converters out of the box.





The camel-file-watch-source source connector has no transforms out of the box.





The camel-file-watch-source source connector has no aggregation strategies out of the box.




// kafka-connector options: END
