// kafka-connector options: START
[[camel-exec-sink-kafka-connector-sink]]
= camel-exec-sink-kafka-connector sink configuration

Connector Description: Execute system commands

The Kamelet expects the following headers to be set:

- `args` / `ce-args`: as the args to be set on the executable.

If the header won't be set the executable will be run without arguments.

When using camel-exec-sink-kafka-connector as sink make sure to use the following Maven dependency to have support for the connector:

[source,xml]
----
<dependency>
  <groupId>org.apache.camel.kafkaconnector</groupId>
  <artifactId>camel-exec-sink-kafka-connector</artifactId>
  <version>x.x.x</version>
  <!-- use the same version as your Camel Kafka connector version -->
</dependency>
----

To use this Sink connector in Kafka connect you'll need to set the following connector.class

[source,java]
----
connector.class=org.apache.camel.kafkaconnector.execsink.CamelExecsinkSinkConnector
----


The camel-exec-sink sink connector supports 1 options, which are listed below.



[width="100%",cols="2,5,^1,1,1",options="header"]
|===
| Name | Description | Default | Required | Priority
| *camel.kamelet.exec-sink.executable* | The command to execute | null | true | HIGH
|===



The camel-exec-sink sink connector has no converters out of the box.





The camel-exec-sink sink connector has no transforms out of the box.





The camel-exec-sink sink connector has no aggregation strategies out of the box.




// kafka-connector options: END
